name: "Tofu :: Proxmox LXC"

on:
  push:
    branches: ["main"]
    paths: ["proxmox/lxc/**"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TOFU_VERSION: "1.10.3"

jobs:
  plan:
    name: "ðŸ§ª Plan Proxmox LXC"
    runs-on: self-hosted
    defaults:
      run:
        working-directory: proxmox/lxc

    steps:
      - name: ðŸ§¾ Checkout
        uses: actions/checkout@v5

      - name: ðŸ” Get secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            64cc2302-5345-4eea-8c9a-b3390140117c > AWS_ACCESS_KEY_ID
            6184035e-bb14-488a-b14e-b33901403af8 > AWS_SECRET_ACCESS_KEY
            39ae0a9d-3c4a-4fe2-ab2c-b3390146b9c0 > TF_VAR_pm_api_token_id
            27f15dbb-21b7-4c76-963a-b3390146cdae > TF_VAR_pm_api_token_secret
            40c480b8-7b2f-45e0-b9c9-b3390146166a > TF_VAR_proxmox_endpoint
            7b7fc7c6-abd9-4b08-8c0a-b339014ab4e3 > TF_VAR_ssh_authorized_key

      - name: ðŸ›  Install OpenTofu
        uses: opentofu/setup-opentofu@v1.0.6
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: âš™ï¸ Init & Plan
        run: |
          tofu init -input=false
          tofu plan -out=tfplan.binary

      - name: ðŸ“¦ Save Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-proxmox-lxc
          path: proxmox/lxc/tfplan.binary

  apply:
    name: "ðŸš€ Apply Proxmox LXC Infra"
    needs: plan
    runs-on: self-hosted
    environment:
      name: manual-approval
    defaults:
      run:
        working-directory: proxmox/lxc

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v5
        with:
          name: tfplan-proxmox-lxc
          path: proxmox/lxc

      - name: ðŸ” Get secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            64cc2302-5345-4eea-8c9a-b3390140117c > AWS_ACCESS_KEY_ID
            6184035e-bb14-488a-b14e-b33901403af8 > AWS_SECRET_ACCESS_KEY
            39ae0a9d-3c4a-4fe2-ab2c-b3390146b9c0 > TF_VAR_pm_api_token_id
            27f15dbb-21b7-4c76-963a-b3390146cdae > TF_VAR_pm_api_token_secret
            40c480b8-7b2f-45e0-b9c9-b3390146166a > TF_VAR_proxmox_endpoint
            7b7fc7c6-abd9-4b08-8c0a-b339014ab4e3 > TF_VAR_ssh_authorized_key

      - uses: opentofu/setup-opentofu@v1.0.6
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: âœ… Apply Plan
        run: tofu apply tfplan.binary
