name: "Tofu :: Proxmox LXC"

on:
  push:
    branches: ["main"]
    paths: ["proxmox/lxc/**"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  TOFU_VERSION: "1.10.3"

jobs:
  plan:
    name: "ðŸ§ª Plan"
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    defaults:
      run:
        working-directory: proxmox/lxc

    steps:
      - name: ðŸ§¾ Checkout
        uses: actions/checkout@v5

      - name: ðŸ”„ Install Packages
        run: |
          apt-get -y update
          apt-get -y install ca-certificates unzip nodejs git

      - name: ðŸ” Get secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            64cc2302-5345-4eea-8c9a-b3390140117c > AWS_ACCESS_KEY_ID
            6184035e-bb14-488a-b14e-b33901403af8 > AWS_SECRET_ACCESS_KEY
            b74a2635-978c-4618-8c8d-b33a0122d81e > PROXMOX_VE_API_TOKEN
            40c480b8-7b2f-45e0-b9c9-b3390146166a > PROXMOX_VE_ENDPOINT
            7b7fc7c6-abd9-4b08-8c0a-b339014ab4e3 > TF_VAR_ssh_authorized_key

      - name: ðŸ›  Install OpenTofu
        uses: opentofu/setup-opentofu@v1.0.6
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: âš™ï¸ Init & Plan
        run: |
          tofu init -input=false
          tofu plan

  apply:
    name: "ðŸš€ Apply"
    needs: plan
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    environment:
      name: manual-approval
    defaults:
      run:
        working-directory: proxmox/lxc

    steps:
      - name: ðŸ§¾ Checkout
        uses: actions/checkout@v5

      - name: ðŸ”„ Install Packages
        run: |
          apt-get -y update
          apt-get -y install ca-certificates unzip nodejs git
      
      - name: ðŸ” Get secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            64cc2302-5345-4eea-8c9a-b3390140117c > AWS_ACCESS_KEY_ID
            6184035e-bb14-488a-b14e-b33901403af8 > AWS_SECRET_ACCESS_KEY
            b74a2635-978c-4618-8c8d-b33a0122d81e > PROXMOX_VE_API_TOKEN
            40c480b8-7b2f-45e0-b9c9-b3390146166a > PROXMOX_VE_ENDPOINT
            7b7fc7c6-abd9-4b08-8c0a-b339014ab4e3 > TF_VAR_ssh_authorized_key

      - uses: opentofu/setup-opentofu@v1.0.6
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: âœ… Apply Plan
        run: |
          tofu init -input=false
          tofu plan
          tofu apply -auto-approve
